server:
  port: 0


spring:
  profiles:
    active: local
  redis:
    host: localhost
    port: 6379
  application:
    name: chat

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka