server:
  port: 0

kafka:
  bootstrapAddress: 49.50.160.149:9092
  topic:
    chat:
      id: chatId
      name: chat-topic

spring:
  application:
    name: chat

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka