server:
  port: 0


spring:
  profiles:
    active: local
  redis:
    host: localhost
    port: 6379
  application:
    name: chat
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
      path: /chat/h2-console
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:dining:chat
    username: sa


eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka