version: '3.4'

services:
  mariadb:
    image: mariadb
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=1234
    networks:
      - default
  redis:
    image: redis:alpine
    ports:
      - '6379:6379'
    networks:
      - default
  rabbitmq:
    image: rabbitmq:3.8.20-management
    ports:
      - '15672:15672'
      - '5672:5672'
      - '15671:15671'
      - '5671:5671'
      - '4369:4369'
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    networks:
      - default

networks:
  default:
    external:
      name: Dining-together
