server:
  port: 0

storage:
  credentials:
    accessKey: PwaPlllZUGTKtO3HJVtp
    secretKey: DW4BHX246JR5Efi928hRsCtvHtC0sCKIOx9OAdbn
  s3:
    bucket: diningtogether
    region: kr-standard
    endPoint: https://kr.object.ncloudstorage.com

logback:
  destination:
    url: 49.50.160.149
    port: 5000

kafka:
  bootstrapAddress: 49.50.160.149:9092
  topic:
    general:
      id: generalId
      name: general-topic
    auction:
      id: auctionId
      name: auction-topic
    store:
      id: storeId
      name: member-topic
    review:
      id: reviewId
      name: review-topic

spring:
  application:
    name: auction
  rabbitmq:
    host: 49.50.163.150
    port: 5672
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
      path: /auction/h2-console
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://49.50.160.149:3306/auction

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

management:
  security:
    enabled: false
  endpoints:
    health:
      show-details: always
    web:
      exposure:
        include: refresh,health,beans,httptrace,busrefresh
