server:
  port: 0

kafka:
  bootstrapAddress: 118.67.133.150:9092
  topic:
    general:
      id: generalId
      name: general-topic
    auction:
      id: auctionId
      name: auction-topic
    store:
      id: storeId
      name: member-topic
    review:
      id: reviewId
      name: review-topic

spring:
  application:
    name: member
  rabbitmq:
    host: 49.50.167.119
    port: 5672
    username: guest
    password: guest
  redis:
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 2
    host: 118.67.133.150
    port: 6379
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
      path: /member/h2-console
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://118.67.133.150:3306/member
    username: root
    password: 1234
  mail:
    host: smtp.gmail.com
    port: 587
    username: moamoa202105@gmail.com
    password: moa1234!
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            required: true
          auth: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
  logging:
    level:
      org.hibernate.SQL: debug
  web:
    resources:
      static-locations: classpath:/static/


eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
management:
  security:
    enabled: false
  endpoints:
    health:
      show-details: always
    web:
      exposure:
        include: refresh,health,beans,httptrace,busrefresh