server:
  port: 8000

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: gateway-server
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
  cloud:
    gateway:
      default-filters:
        - name: GlobalFilter
          args:
            baseMessage: Spring Cloud Gateway Global Filter
            preLogger: true
            postLogger: true
      routes:
        - id: member
          uri: lb://MEMBER
          predicates:
            - Path=/member/actuator/**
            - Method=GET,POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/member/(?<segment>.*),/$\{segment}
        - id: member
          uri: lb://MEMBER
          predicates:
            - Path=/member/**
        - id: auction
          uri: lb://AUCTION
          predicates:
            - Path=/auction/**
        - id: search
          uri: lb://SEARCH
          predicates:
            - Path=/search/**
management:
  security:
    enabled: false
  endpoints:
    health:
      show-details: always
    web:
      exposure:
        include: refresh, health, beans,httptrace,busrefresh
#token:
#  secret: secret_token
#  expiration_time: 86400000
