server:
  port: 8000

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      default-filters:
        - name: GlobalFilter
          args:
            baseMessage: Spring Cloud Gateway Global Filter
            preLogger: true
            postLogger: true
      routes:
        - id: member
          uri: lb://MEMBER
          predicates:
            - Path=/member/**
        - id: auction
          uri: lb://AUCTION
          predicates:
            - Path=/auction/**
        - id: search
          uri: lb://SEARCH
          predicates:
            - Path=/search/**

token:
  secret: secret_token
  expiration_time: 86400000
