spring.elasticsearch.rest.uris: http://101.101.216.26:9300
elasticsearch.cluster_name: docker-cluster
spring.main.allow-bean-definition-overriding: true

server:
  port: 0
spring:
  application:
    name: search
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false

kafka:
  bootstrapAddress: 118.67.133.150:9092
  topic:
    general:
      id: generalId
      name: general-topic
    auction:
      id: auctionGroupId
      name: auction-auction-topic
    store:
      id: storeGroupId
      name: member-store-topic

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka